package authentication

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.54

import (
	"context"
	"go-server/authentication/authmodel"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, name string, password string) (*authmodel.AuthenticationInfo, error) {
	return r.Resolver.Login(ctx, name, password)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*authmodel.User, error) {
	return r.Resolver.Users(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
